# The maximum width of a line.
max_width = 100

# Rust can sometimes be very vertical. This setting tells rustfmt
# to try and be a bit more compact horizontally.
use_small_heuristics = "Max"

# Automatically sort `use` statements. This is fantastic for keeping
# imports clean and consistent.
reorder_imports = true
